
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'EQUALS ID LARROW NUMBER RARROW STRING\n    declaration : ID LARROW NUMBER\n                | ID LARROW STRING\n                | ID EQUALS NUMBER\n                | ID EQUALS STRING\n                | NUMBER RARROW ID\n                | STRING RARROW ID\n    '
    
_lr_action_items = {'ID':([0,7,8,],[2,13,14,]),'NUMBER':([0,5,6,],[3,9,11,]),'STRING':([0,5,6,],[4,10,12,]),'$end':([1,9,10,11,12,13,14,],[0,-1,-2,-3,-4,-5,-6,]),'LARROW':([2,],[5,]),'EQUALS':([2,],[6,]),'RARROW':([3,4,],[7,8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> ID LARROW NUMBER','declaration',3,'p_declaration','var_yacc.py',40),
  ('declaration -> ID LARROW STRING','declaration',3,'p_declaration','var_yacc.py',41),
  ('declaration -> ID EQUALS NUMBER','declaration',3,'p_declaration','var_yacc.py',42),
  ('declaration -> ID EQUALS STRING','declaration',3,'p_declaration','var_yacc.py',43),
  ('declaration -> NUMBER RARROW ID','declaration',3,'p_declaration','var_yacc.py',44),
  ('declaration -> STRING RARROW ID','declaration',3,'p_declaration','var_yacc.py',45),
]
