
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN_MISSING C COMMA ID LARROW LIST LPAREN NUM RPAREN STRING\n    declaration : ID LARROW LIST LPAREN values RPAREN\n    \n    values  : types COMMA values\n            | types\n    \n    types   : ID\n            | C LPAREN values RPAREN\n            | STRING\n            | NUM\n            | BOOLEAN_MISSING\n            | LIST LPAREN values RPAREN\n    '
    
_lr_action_items = {'ID':([0,5,14,16,17,],[2,6,6,6,6,]),'$end':([1,15,],[0,-1,]),'LARROW':([2,],[3,]),'LIST':([3,5,14,16,17,],[4,7,7,7,7,]),'LPAREN':([4,7,10,],[5,14,17,]),'C':([5,14,16,17,],[10,10,10,10,]),'STRING':([5,14,16,17,],[11,11,11,11,]),'NUM':([5,14,16,17,],[12,12,12,12,]),'BOOLEAN_MISSING':([5,14,16,17,],[13,13,13,13,]),'COMMA':([6,9,11,12,13,21,22,],[-4,16,-6,-7,-8,-9,-5,]),'RPAREN':([6,8,9,11,12,13,18,19,20,21,22,],[-4,15,-3,-6,-7,-8,21,-2,22,-9,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'values':([5,14,16,17,],[8,18,19,20,]),'types':([5,14,16,17,],[9,9,9,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> ID LARROW LIST LPAREN values RPAREN','declaration',6,'p_declaration','list_yacc.py',47),
  ('values -> types COMMA values','values',3,'p_values','list_yacc.py',52),
  ('values -> types','values',1,'p_values','list_yacc.py',53),
  ('types -> ID','types',1,'p_types','list_yacc.py',58),
  ('types -> C LPAREN values RPAREN','types',4,'p_types','list_yacc.py',59),
  ('types -> STRING','types',1,'p_types','list_yacc.py',60),
  ('types -> NUM','types',1,'p_types','list_yacc.py',61),
  ('types -> BOOLEAN_MISSING','types',1,'p_types','list_yacc.py',62),
  ('types -> LIST LPAREN values RPAREN','types',4,'p_types','list_yacc.py',63),
]
