
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA EQUAL ID LARROW LPAREN NUM RPAREN STRING SWITCH\n    switch  : ID LARROW SWITCH LPAREN expr COMMA cases RPAREN\n            | ID EQUAL SWITCH LPAREN expr COMMA cases RPAREN\n    \n    cases   : STRING COMMA cases\n            | STRING EQUAL STRING COMMA cases \n            | STRING EQUAL STRING\n            | STRING\n    \n    expr    : NUM   \n            | ID\n            \n    '
    
_lr_action_items = {'ID':([0,7,8,],[2,9,9,]),'$end':([1,18,21,],[0,-1,-2,]),'LARROW':([2,],[3,]),'EQUAL':([2,16,],[4,20,]),'SWITCH':([3,4,],[5,6,]),'LPAREN':([5,6,],[7,8,]),'NUM':([7,8,],[11,11,]),'COMMA':([9,10,11,12,16,23,],[-8,13,-7,14,19,24,]),'STRING':([13,14,19,20,24,],[16,16,16,23,16,]),'RPAREN':([15,16,17,22,23,25,],[18,-6,21,-3,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'switch':([0,],[1,]),'expr':([7,8,],[10,12,]),'cases':([13,14,19,24,],[15,17,22,25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> switch","S'",1,None,None,None),
  ('switch -> ID LARROW SWITCH LPAREN expr COMMA cases RPAREN','switch',8,'p_switch','R_switch_lex_yacc.py',45),
  ('switch -> ID EQUAL SWITCH LPAREN expr COMMA cases RPAREN','switch',8,'p_switch','R_switch_lex_yacc.py',46),
  ('cases -> STRING COMMA cases','cases',3,'p_cases','R_switch_lex_yacc.py',51),
  ('cases -> STRING EQUAL STRING COMMA cases','cases',5,'p_cases','R_switch_lex_yacc.py',52),
  ('cases -> STRING EQUAL STRING','cases',3,'p_cases','R_switch_lex_yacc.py',53),
  ('cases -> STRING','cases',1,'p_cases','R_switch_lex_yacc.py',54),
  ('expr -> NUM','expr',1,'p_expr','R_switch_lex_yacc.py',59),
  ('expr -> ID','expr',1,'p_expr','R_switch_lex_yacc.py',60),
]
