
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN_MISSING BY C COLON COMMA EQUAL ID LARROW LEN LPAREN NUMBER RPAREN SEQ STRING\n    declaration : ID LARROW C LPAREN list RPAREN\n                | ID LARROW NUMBER COLON NUMBER\n                | ID LARROW SEQ LPAREN NUMBER COMMA NUMBER COMMA BY EQUAL NUMBER RPAREN\n                | ID LARROW SEQ LPAREN NUMBER COMMA NUMBER COMMA LEN EQUAL NUMBER RPAREN\n    \n    list    :   NUMBER \n            |   STRING\n            |   BOOLEAN_MISSING\n            |   NUMBER COMMA list\n            |   STRING COMMA list\n            |   BOOLEAN_MISSING COMMA list\n    '
    
_lr_action_items = {'ID':([0,],[2,]),'$end':([1,14,16,32,33,],[0,-2,-1,-3,-4,]),'LARROW':([2,],[3,]),'C':([3,],[4,]),'NUMBER':([3,7,8,9,17,18,19,20,28,29,],[5,11,14,15,11,11,11,24,30,31,]),'SEQ':([3,],[6,]),'LPAREN':([4,6,],[7,9,]),'COLON':([5,],[8,]),'STRING':([7,17,18,19,],[12,12,12,12,]),'BOOLEAN_MISSING':([7,17,18,19,],[13,13,13,13,]),'RPAREN':([10,11,12,13,21,22,23,30,31,],[16,-5,-6,-7,-8,-9,-10,32,33,]),'COMMA':([11,12,13,15,24,],[17,18,19,20,25,]),'BY':([25,],[26,]),'LEN':([25,],[27,]),'EQUAL':([26,27,],[28,29,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'declaration':([0,],[1,]),'list':([7,17,18,19,],[10,21,22,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> declaration","S'",1,None,None,None),
  ('declaration -> ID LARROW C LPAREN list RPAREN','declaration',6,'p_declaration','vector_yacc.py',10),
  ('declaration -> ID LARROW NUMBER COLON NUMBER','declaration',5,'p_declaration','vector_yacc.py',11),
  ('declaration -> ID LARROW SEQ LPAREN NUMBER COMMA NUMBER COMMA BY EQUAL NUMBER RPAREN','declaration',12,'p_declaration','vector_yacc.py',12),
  ('declaration -> ID LARROW SEQ LPAREN NUMBER COMMA NUMBER COMMA LEN EQUAL NUMBER RPAREN','declaration',12,'p_declaration','vector_yacc.py',13),
  ('list -> NUMBER','list',1,'p_list','vector_yacc.py',20),
  ('list -> STRING','list',1,'p_list','vector_yacc.py',21),
  ('list -> BOOLEAN_MISSING','list',1,'p_list','vector_yacc.py',22),
  ('list -> NUMBER COMMA list','list',3,'p_list','vector_yacc.py',23),
  ('list -> STRING COMMA list','list',3,'p_list','vector_yacc.py',24),
  ('list -> BOOLEAN_MISSING COMMA list','list',3,'p_list','vector_yacc.py',25),
]
